[package]
name = "bins_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neovim-lib = "0.6.0"
serde = "1.0.152"
serde_derive = "1.0.152"
serde_json = "1.0.93"
